### ISSUE TITLE
Grid: --reversable modifier

### ISSUE THREAD

**Issue by jedrzejchalubek** [bemoid/bemoid#13]
```scss
&--reversable {
    @media (max-width: get-breakpoint(medium)) {
      flex-direction: row-reverse;

      &#{$this}--stackable {
        @media (max-width: get-breakpoint(medium)) {
          flex-direction: column-reverse;
        }
      }
    }
  }
```
