### ISSUE TITLE
Container: Introduce --stretch modifier class

### ISSUE THREAD

**Issue by jedrzejchalubek** [bemoid/bemoid#18]
`--stretch` should be responsive for expanding container to 100% height

```scss
&--stretch {
    height: 100%;
  }
```
