### ISSUE TITLE
Introduce `expanded` modifier class on item element in group component

### ISSUE THREAD

**Issue by jedrzejchalubek** [bemoid/bemoid#4]
`--expanded` modifier class on `.group__item` should replace flex with extending one:

```scss
&__item {
  &--expanded {
    flex: 1 0 auto;
  }
}
```
