### ISSUE TITLE
Make group behave as block as default

### ISSUE THREAD

**Issue by jedrzejchalubek** [bemoid/bemoid#5]
`.group` should behave as block

```scss
.group {
  display: flex;
}
```

After this change, we should introduce a `.group--inlined` modifier as option for making group inline  once again.

```scss
.group {
  &--inlined {
    display: inline-flex;
  }
}
```
