### ISSUE TITLE
Refactor hidden and visible utilities

### ISSUE THREAD

**Issue by jedrzejchalubek** [bemoid/bemoid#8]
Here is a targeted structure

```scss
.hidden {
  display: initial;

  &\@medium {
    @include breakpoint(medium down) {
      display: none !important;
    }
  }
}
```

```scss
.visible {
  display: none;

  &\@medium {
    @include breakpoint(medium down) {
      display: initial !important;
    }
  }
}
```
